### PR TITLE
[SYCL] Add tests for atomic_ref memory orders

### LINKED ISSUE #793: Implement tests for atomic memory orders
Existing tests are fundamentally broken and are being removed in https://github.com/intel/llvm-test-suite/pull/783. New tests need to be designed and implemented.

### PR DESCRIPTION
**Pull request by t4c1**
Adds tests for various memory orders. These tests are not ideal, as they do not in fact fail if run with more a relaxed memory order. 

Closes https://github.com/intel/llvm-test-suite/issues/793.

### CODE REVIEW

File: SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp [hunk 1]
```diff
@@ -1,33 +1,239 @@
...
 
 #include "atomic_memory_order.h"
 #include <iostream>
+#include <numeric>
 using namespace sycl;
 
-int main() {
+template <memory_order order> void test_acquire_global() {
+  const size_t N_items = 1024;
+  const size_t N_iters = 100000;
```
Comment (steffenlarsen) [inline SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: I think maybe this is a few too many iterations, especially since we run the test a couple of times. I realize it will decrease the chances of finding a bug, but if there is a bug I suspect we would run it often enough to at least see it fail occasionally.

Comment (t4c1) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: I am fine with reducing the number of iterations. What number would you like to see? Also let me just point out that the test is still relatively fast, despite seemingly high number of iterations.

Comment (steffenlarsen) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: I would probably just cut a 0, but if it isn't that bad w.r.t execution time then maybe its okay. How long is the execution time in comparison to AtomicRef/add.cpp?

Comment (t4c1) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: On Titan RTX this takes 9.4 seconds and AtomicRef/add.cpp takes 10.7 (this is with the PR reducing coverage already merged). Cutting a 0 in each of the tests makes this go down to 8.9 seconds.

Comment (steffenlarsen) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: AtomicRef/add.cpp is currently the longest running test in the test-suite, so 8.9s still seems like a lot. @alexbatashev may have some ideas?

File: SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp [hunk 2]
```diff
@@ -1,33 +1,239 @@
...
 // RUN: %GPU_RUN_PLACEHOLDER %t.out
 // RUN: %ACC_RUN_PLACEHOLDER %t.out
 // L0, OpenCL, and HIP backends don't currently support
 // info::device::atomic_memory_order_capabilities
-// UNSUPPORTED: level_zero || opencl || hip
+// UNSUPPORTED: level_zero, opencl, hip
 
-// NOTE: Tests load and store for acquire-release memory ordering.
+// host does not support barrier
+// XFAIL: host
```
Comment (alexbatashev) [inline SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp:11]: Maybe we just remove the %HOST_RUN_... line?

File: SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp (hunk 1 above)
Comment (alexbatashev) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: Maybe if we somehow reduce the number of kernels submitted, that would help? I.e. if we factor out kernel body instead of kernel submission function.

File: SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp (hunk 2 above)
Comment (t4c1) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp:11]: It only shaves of 0.2 seconds.

File: SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp (hunk 1 above)
Comment (t4c1) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: The kernels are actually different. I tried grouping all the tests for each memory order into one kernel, but it makes the code a bit less readable, while reducing the test runtime by 1.5s. I am not sure if that is worth it.

Comment (t4c1) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: @steffenlarsen what is your preference here - how much should we adapt the code for minimal running time?

Comment (steffenlarsen) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: I'm thinking maybe it's best if we make it do 1000 iterations and live with whatever cost that has. I understand that 1000 iterations isn't necessarily a lot when testing for something like this, but hopefully with the amount that it will be run we will eventually find bugs here. Are you okay with that approach?

Comment (t4c1) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: I am fine with that. So you do not think merging kernels is worthwhile as it comes at expense of readability?

Comment (t4c1) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: @steffenlarsen which direction would you like me to take with this? Keep it as it is or merge multiple kernels?

Comment (steffenlarsen) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: Oh, apologies. I honestly thought I had responded. I am okay with keeping them as multiple kernels for the sake of readability.

Comment (t4c1) [reply SYCL/AtomicRef/atomic_memory_order_acq_rel.cpp]: I reduced the number of operations to 1000.

**Review by steffenlarsen — APPROVED** [review]

**Comment by t4c1** [comment]
Does this need any more reviews?
